[package]
name = "my_dist_launcher"
version = "0.1.0"
edition = "2024"

[dependencies]
slint = { version = "1.18.1", default-features = false, features = ["backend-winit", "renderer-software", "compat-1-2"] }
serde = { version = "1", features = ["derive"] }
toml = { version = "0.8" }
dirs = "6"

[build-dependencies]
slint-build = { version = "1.18.1", default-features = false, features = ["renderer-software", "compat-1-18"] }

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
strip = true
panic = "abort"
